# Feature Engineering & Feature Extraction

## Attaching Resources

### Importing Necessary Libraries

In [12]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

### Adding Dataset

#### Adding Train Dataset

In [13]:
wby = pd.read_csv('https://raw.githubusercontent.com/kunal-mallick/Wild-Blueberry-Yield/main/Data%20Preprocessing%20%26%20EDA/EDA.csv')

wby

clonesize  honeybee  bumbles  andrena  osmia  MaxOfUpperTRange  \
0           25.0      0.50     0.25     0.75   0.50              69.7   
1           25.0      0.50     0.25     0.50   0.50              69.7   
2           12.5      0.25     0.25     0.63   0.63              86.0   
3           12.5      0.25     0.25     0.63   0.50              77.4   
4           25.0      0.50     0.25     0.63   0.63              77.4   
...          ...       ...      ...      ...    ...               ...   
15100       12.5      0.25     0.25     0.38   0.50              77.4   
15101       12.5      0.25     0.25     0.25   0.50              86.0   
15102       25.0      0.50     0.25     0.38   0.75              77.4   
15103       25.0      0.50     0.25     0.63   0.63              69.7   
15104       25.0      0.50     0.25     0.63   0.50              77.4   

       MinOfUpperTRange  AverageOfUpperTRange  MaxOfLowerTRange  \
0                  42.1                  58.2              50.2   
1                  42.1                  58.2              50.2   
2                  52.0                  71.9              62.0   
3                  46.8                  64.7              55.8   
4                  46.8                  64.7              55.8   
...                 ...                   ...               ...   
15100              46.8                  64.7              55.8   
15101              52.0                  71.9              62.0   
15102              46.8                  64.7              55.8   
15103              42.1                  58.2              50.2   
15104              46.8                  64.7              55.8   

       MinOfLowerTRange  AverageOfLowerTRange  RainingDays  \
0                  24.3                  41.2         24.0   
1                  24.3                  41.2         24.0   
2                  30.0                  50.8         24.0   
3                  27.0                  45.8         24.0   
4                  27.0                  45.8         24.0   
...                 ...                   ...          ...   
15100              27.0                  45.8         16.0   
15101              30.0                  50.8         34.0   
15102              27.0                  45.8         34.0   
15103              24.3                  41.2         24.0   
15104              27.0                  45.8         16.0   

       AverageRainingDays  fruitset  fruitmass      seeds       yield  
0                    0.39  0.425011   0.417545  32.460887  4476.81146  
1                    0.39  0.444908   0.422051  33.858317  5548.12201  
2                    0.39  0.552927   0.470853  38.341781  6869.77760  
3                    0.39  0.565976   0.478137  39.467561  6880.77590  
4                    0.39  0.579677   0.494165  40.484512  7479.93417  
...                   ...       ...        ...        ...         ...  
15100                0.26  0.556302   0.476308  40.546480  7667.83619  
15101                0.56  0.354413   0.388145  29.467434  3680.56025  
15102                0.56  0.422548   0.416786  32.299059  4696.44394  
15103                0.39  0.542170   0.434133  36.674243  6772.93347  
15104                0.26  0.492077   0.446576  35.094733  5867.99722  

[15105 rows x 17 columns]

#### Adding Test Dataset

In [14]:
xtest_raw = pd.read_csv('https://raw.githubusercontent.com/kunal-mallick/Wild-Blueberry-Yield/main/resources/xtest.csv')
xtest_raw.drop(columns='id', inplace=True)

xtest_raw

clonesize  honeybee  bumbles  andrena  osmia  MaxOfUpperTRange  \
0           25.0      0.25     0.25     0.25   0.25              86.0   
1           12.5      0.25     0.25     0.75   0.63              94.6   
2           12.5      0.25     0.25     0.63   0.63              86.0   
3           25.0      0.50     0.38     0.38   0.63              86.0   
4           37.5      0.75     0.25     0.25   0.25              94.6   
...          ...       ...      ...      ...    ...               ...   
10189       25.0      0.25     0.25     0.25   0.25              86.0   
10190       25.0      0.50     0.25     0.50   0.75              77.4   
10191       25.0      0.50     0.38     0.50   0.50              77.4   
10192       12.5      0.25     0.25     0.38   0.50              94.6   
10193       12.5      0.25     0.25     0.50   0.50              77.4   

       MinOfUpperTRange  AverageOfUpperTRange  MaxOfLowerTRange  \
0                  52.0                  71.9              62.0   
1                  57.2                  79.0              68.2   
2                  52.0                  71.9              62.0   
3                  52.0                  71.9              62.0   
4                  57.2                  79.0              68.2   
...                 ...                   ...               ...   
10189              52.0                  71.9              62.0   
10190              46.8                  64.7              55.8   
10191              46.8                  64.7              55.8   
10192              57.2                  79.0              68.2   
10193              46.8                  64.7              55.8   

       MinOfLowerTRange  AverageOfLowerTRange  RainingDays  \
0                  30.0                  50.8         24.0   
1                  33.0                  55.9          1.0   
2                  30.0                  50.8         16.0   
3                  30.0                  50.8         16.0   
4                  33.0                  55.9         24.0   
...                 ...                   ...          ...   
10189              30.0                  50.8         24.0   
10190              27.0                  45.8         16.0   
10191              27.0                  45.8         16.0   
10192              33.0                  55.9         34.0   
10193              27.0                  45.8          1.0   

       AverageRainingDays  fruitset  fruitmass      seeds  
0                    0.39  0.399367   0.408088  31.394569  
1                    0.10  0.488048   0.442866  36.846956  
2                    0.26  0.583379   0.487057  40.037644  
3                    0.26  0.433014   0.422847  33.116091  
4                    0.39  0.360996   0.388860  29.558019  
...                   ...       ...        ...        ...  
10189                0.39  0.474162   0.437923  34.525258  
10190                0.26  0.482854   0.440676  35.648221  
10191                0.26  0.568854   0.463065  37.724724  
10192                0.56  0.407374   0.409261  31.881847  
10193                0.10  0.579677   0.486202  40.265408  

[10194 rows x 16 columns]

In [15]:
ytest = pd.read_csv('https://raw.githubusercontent.com/kunal-mallick/Wild-Blueberry-Yield/main/resources/ytest.csv')
ytest.drop(columns='id', inplace=True)

ytest

yield
0      6025.194
1      6025.194
2      6025.194
3      6025.194
4      6025.194
...         ...
10189  6025.194
10190  6025.194
10191  6025.194
10192  6025.194
10193  6025.194

[10194 rows x 1 columns]

## Splitting The Data Into Target and Independent set

In [16]:
x = wby.iloc[:,:-1]
ytrain = wby['yield']

In [17]:
x

clonesize  honeybee  bumbles  andrena  osmia  MaxOfUpperTRange  \
0           25.0      0.50     0.25     0.75   0.50              69.7   
1           25.0      0.50     0.25     0.50   0.50              69.7   
2           12.5      0.25     0.25     0.63   0.63              86.0   
3           12.5      0.25     0.25     0.63   0.50              77.4   
4           25.0      0.50     0.25     0.63   0.63              77.4   
...          ...       ...      ...      ...    ...               ...   
15100       12.5      0.25     0.25     0.38   0.50              77.4   
15101       12.5      0.25     0.25     0.25   0.50              86.0   
15102       25.0      0.50     0.25     0.38   0.75              77.4   
15103       25.0      0.50     0.25     0.63   0.63              69.7   
15104       25.0      0.50     0.25     0.63   0.50              77.4   

       MinOfUpperTRange  AverageOfUpperTRange  MaxOfLowerTRange  \
0                  42.1                  58.2              50.2   
1                  42.1                  58.2              50.2   
2                  52.0                  71.9              62.0   
3                  46.8                  64.7              55.8   
4                  46.8                  64.7              55.8   
...                 ...                   ...               ...   
15100              46.8                  64.7              55.8   
15101              52.0                  71.9              62.0   
15102              46.8                  64.7              55.8   
15103              42.1                  58.2              50.2   
15104              46.8                  64.7              55.8   

       MinOfLowerTRange  AverageOfLowerTRange  RainingDays  \
0                  24.3                  41.2         24.0   
1                  24.3                  41.2         24.0   
2                  30.0                  50.8         24.0   
3                  27.0                  45.8         24.0   
4                  27.0                  45.8         24.0   
...                 ...                   ...          ...   
15100              27.0                  45.8         16.0   
15101              30.0                  50.8         34.0   
15102              27.0                  45.8         34.0   
15103              24.3                  41.2         24.0   
15104              27.0                  45.8         16.0   

       AverageRainingDays  fruitset  fruitmass      seeds  
0                    0.39  0.425011   0.417545  32.460887  
1                    0.39  0.444908   0.422051  33.858317  
2                    0.39  0.552927   0.470853  38.341781  
3                    0.39  0.565976   0.478137  39.467561  
4                    0.39  0.579677   0.494165  40.484512  
...                   ...       ...        ...        ...  
15100                0.26  0.556302   0.476308  40.546480  
15101                0.56  0.354413   0.388145  29.467434  
15102                0.56  0.422548   0.416786  32.299059  
15103                0.39  0.542170   0.434133  36.674243  
15104                0.26  0.492077   0.446576  35.094733  

[15105 rows x 16 columns]

### Normalizing The Dataset

In [18]:
sc = StandardScaler()
xtrain  = pd.DataFrame(sc.fit_transform(x), columns=x.columns)

In [19]:
xtrain

clonesize  honeybee  bumbles   andrena     osmia  MaxOfUpperTRange  \
0       0.816825  0.919968  -0.6364  1.736879 -0.711751         -1.358940   
1       0.816825  0.919968  -0.6364  0.039427 -0.711751         -1.358940   
2      -1.089681 -1.031541  -0.6364  0.922102  0.254834          0.422722   
3      -1.089681 -1.031541  -0.6364  0.922102 -0.711751         -0.517296   
4       0.816825  0.919968  -0.6364  0.922102  0.254834         -0.517296   
...          ...       ...      ...       ...       ...               ...   
15100  -1.089681 -1.031541  -0.6364 -0.775349 -0.711751         -0.517296   
15101  -1.089681 -1.031541  -0.6364 -1.658024 -0.711751          0.422722   
15102   0.816825  0.919968  -0.6364 -0.775349  1.147067         -0.517296   
15103   0.816825  0.919968  -0.6364  0.922102  0.254834         -1.358940   
15104   0.816825  0.919968  -0.6364  0.922102 -0.711751         -0.517296   

       MinOfUpperTRange  AverageOfUpperTRange  MaxOfLowerTRange  \
0             -1.361048             -1.363895         -1.361524   
1             -1.361048             -1.363895         -1.361524   
2              0.423476              0.428451          0.423063   
3             -0.513850             -0.513512         -0.514601   
4             -0.513850             -0.513512         -0.514601   
...                 ...                   ...               ...   
15100         -0.513850             -0.513512         -0.514601   
15101          0.423476              0.428451          0.423063   
15102         -0.513850             -0.513512         -0.514601   
15103         -1.361048             -1.363895         -1.361524   
15104         -0.513850             -0.513512         -0.514601   

       MinOfLowerTRange  AverageOfLowerTRange  RainingDays  \
0             -1.360264             -1.362562     0.439451   
1             -1.360264             -1.362562     0.439451   
2              0.423162              0.417933     0.439451   
3             -0.515483             -0.509408     0.439451   
4             -0.515483             -0.509408     0.439451   
...                 ...                   ...          ...   
15100         -0.515483             -0.509408    -0.314985   
15101          0.423162              0.417933     1.382496   
15102         -0.515483             -0.509408     1.382496   
15103         -1.360264             -1.362562     0.439451   
15104         -0.515483             -0.509408    -0.314985   

       AverageRainingDays  fruitset  fruitmass     seeds  
0                0.403670 -1.105867  -0.819688 -0.953478  
1                0.403670 -0.829223  -0.695479 -0.600662  
2                0.403670  0.672616   0.649740  0.531298  
3                0.403670  0.854053   0.850516  0.815528  
4                0.403670  1.044533   1.292335  1.072282  
...                   ...       ...        ...       ...  
15100           -0.392652  0.719540   0.800123  1.087928  
15101            1.445015 -2.087426  -1.630106 -1.709248  
15102            1.445015 -1.140114  -0.840633 -0.994335  
15103            0.403670  0.523062  -0.362462  0.110287  
15104           -0.392652 -0.173413  -0.019461 -0.288499  

[15105 rows x 16 columns]

In [20]:
xtest = pd.DataFrame(sc.fit_transform(xtest_raw), columns=xtest_raw.columns)

In [21]:
xtest

clonesize  honeybee   bumbles   andrena     osmia  MaxOfUpperTRange  \
0       0.789503 -0.363088 -0.606503 -1.628845 -2.453506          0.414398   
1      -1.106867 -0.363088 -0.606503  1.745905  0.262907          1.353982   
2      -1.106867 -0.363088 -0.606503  0.935965  0.262907          0.414398   
3       0.789503  0.277932  1.565100 -0.751410  0.262907          0.414398   
4       2.685873  0.918953 -0.606503 -1.628845 -2.453506          1.353982   
...          ...       ...       ...       ...       ...               ...   
10189   0.789503 -0.363088 -0.606503 -1.628845 -2.453506          0.414398   
10190   0.789503  0.277932 -0.606503  0.058530  1.120722         -0.525185   
10191   0.789503  0.277932  1.565100  0.058530 -0.666392         -0.525185   
10192  -1.106867 -0.363088 -0.606503 -0.751410 -0.666392          1.353982   
10193  -1.106867 -0.363088 -0.606503  0.058530 -0.666392         -0.525185   

       MinOfUpperTRange  AverageOfUpperTRange  MaxOfLowerTRange  \
0              0.414768              0.420044          0.414636   
1              1.351365              1.348482          1.351655   
2              0.414768              0.420044          0.414636   
3              0.414768              0.420044          0.414636   
4              1.351365              1.348482          1.351655   
...                 ...                   ...               ...   
10189          0.414768              0.420044          0.414636   
10190         -0.521829             -0.521470         -0.522383   
10191         -0.521829             -0.521470         -0.522383   
10192          1.351365              1.348482          1.351655   
10193         -0.521829             -0.521470         -0.522383   

       MinOfLowerTRange  AverageOfLowerTRange  RainingDays  \
0              0.414374              0.409109     0.466288   
1              1.352424              1.354337    -1.486257   
2              0.414374              0.409109    -0.212858   
3              0.414374              0.409109    -0.212858   
4              1.352424              1.354337     0.466288   
...                 ...                   ...          ...   
10189          0.414374              0.409109     0.466288   
10190         -0.523675             -0.517585    -0.212858   
10191         -0.523675             -0.517585    -0.212858   
10192          1.352424              1.354337     1.315221   
10193         -0.523675             -0.517585    -1.486257   

       AverageRainingDays  fruitset  fruitmass     seeds  
0                0.408256 -1.371318  -1.032509 -1.179639  
1               -1.345772 -0.184207  -0.093898  0.176782  
2               -0.378032  1.091922   1.098780  0.970547  
3               -0.378032 -0.920904  -0.634191 -0.751366  
4                0.408256 -1.884969  -1.551449 -1.636527  
...                   ...       ...        ...       ...  
10189            0.408256 -0.370084  -0.227301 -0.400800  
10190           -0.378032 -0.253732  -0.153004 -0.121434  
10191           -0.378032  0.897483   0.451253  0.395149  
10192            1.436480 -1.264140  -1.000865 -1.058416  
10193           -1.345772  1.042365   1.075698  1.027209  

[10194 rows x 16 columns]

## Performing Dimension Reductionality

### Creating PCA With Default Value

In [22]:
pca_def = PCA()
pcs_def = pca_def.fit_transform(xtrain)
pcs_def

array([[-3.54723572e+00,  1.72176105e+00,  7.83004250e-01, ...,
        -3.89881106e-03, -1.84955968e-03, -2.70826732e-03],
       [-3.49183700e+00,  1.40331896e+00,  3.17956335e-01, ...,
        -3.49391911e-03, -1.81063097e-03, -2.45957749e-03],
       [ 1.15862196e+00, -9.29251119e-01, -1.05616191e+00, ...,
        -4.52997430e-04, -3.12197244e-03,  6.63678828e-03],
       ...,
       [-1.53517135e+00,  2.57404826e+00,  2.22870140e-01, ...,
         4.29970805e-03,  3.29783230e-03, -1.60929738e-03],
       [-3.35576102e+00,  2.36571932e-01,  1.04749617e+00, ...,
        -1.24750729e-03, -6.17387013e-04, -9.08659793e-04],
       [-1.28785263e+00,  3.55409878e-01,  1.00812933e+00, ...,
         3.34455729e-03,  3.39236676e-03, -1.80127592e-03]])

In [23]:
pca_def.explained_variance_ratio_

array([3.78124694e-01, 2.52314949e-01, 1.14084659e-01, 8.05930789e-02,
       7.50859828e-02, 4.98596993e-02, 3.53959850e-02, 6.81158861e-03,
       4.26173175e-03, 3.14010850e-03, 1.38157887e-04, 1.28981931e-04,
       4.22569573e-05, 1.48226759e-05, 1.90222141e-06, 1.40151762e-06])

In [24]:
np.cumsum(pca_def.explained_variance_ratio_)

array([0.37812469, 0.63043964, 0.7445243 , 0.82511738, 0.90020336,
       0.95006306, 0.98545905, 0.99227064, 0.99653237, 0.99967248,
       0.99981063, 0.99993962, 0.99998187, 0.9999967 , 0.9999986 ,
       1.        ])

- As it is clear that 99% of the data came from the first column alone, we will use n component 8.

### Creating PCA With 3 Component For Xtrain

In [25]:
pca_8 = PCA(n_components = 8)
pcs_8 = pca_8.fit_transform(xtrain)
pcs_8

array([[-3.54723572,  1.72176105,  0.78300425, ...,  0.8222103 ,
         1.06198658,  0.06128938],
       [-3.491837  ,  1.40331896,  0.31795633, ...,  0.93179013,
        -0.09461803,  0.17355022],
       [ 1.15862196, -0.92925112, -1.05616191, ...,  0.09313806,
         0.26207836, -0.06745735],
       ...,
       [-1.53517135,  2.57404826,  0.22287014, ..., -0.25056613,
        -1.51925071,  0.04121405],
       [-3.35576102,  0.23657193,  1.04749617, ...,  0.99222325,
        -0.13893932,  0.03968789],
       [-1.28785263,  0.35540988,  1.00812933, ...,  1.05496453,
         0.43043557,  0.11781913]])

#### Creating DataFrame

In [26]:
def col_pc_n(n):

    col = []
    p = 'pc'

    for i in range(0,n):
        col_n = p + str(i)
        col.append(col_n)

    return col

In [27]:
wn_scaled_pca = pd.DataFrame(pcs_8, columns=col_pc_n(8))

wn_scaled_pca

pc0       pc1       pc2       pc3       pc4       pc5       pc6  \
0     -3.547236  1.721761  0.783004 -0.360791 -1.231114  0.822210  1.061987   
1     -3.491837  1.403319  0.317956  0.340913 -0.286576  0.931790 -0.094618   
2      1.158622 -0.929251 -1.056162 -1.541264 -0.608161  0.093138  0.262078   
3     -1.063520 -1.406425 -1.349643 -1.239193 -0.427389  0.982451  0.674583   
4     -1.040946 -0.903774  1.199010 -1.458922  0.074867  1.750173 -0.331411   
...         ...       ...       ...       ...       ...       ...       ...   
15100 -1.019800 -1.979337 -1.493230  0.281778 -0.032021  0.642453 -0.394220   
15101  0.623028  3.122603 -3.000952  0.522615  0.104610 -1.013185 -0.543093   
15102 -1.535171  2.574048  0.222870 -0.855221  0.469169 -0.250566 -1.519251   
15103 -3.355761  0.236572  1.047496 -0.956048 -0.363547  0.992223 -0.138939   
15104 -1.287853  0.355410  1.008129  0.363049 -0.965946  1.054965  0.430436   

            pc7  
0      0.061289  
1      0.173550  
2     -0.067457  
3      0.009827  
4     -0.050655  
...         ...  
15100  0.126622  
15101  0.256200  
15102  0.041214  
15103  0.039688  
15104  0.117819  

[15105 rows x 8 columns]

### Creating PCA With 3 Component For Xtest

In [28]:
pca_8 = PCA(n_components = 8)
pcs_8_xtest = pca_8.fit_transform(xtest)
pcs_8_xtest

array([[-0.7927398 ,  2.63181168,  1.04124108, ...,  0.17159132,
        -0.82325872, -0.35373486],
       [-3.35400905, -1.00044363,  0.44776983, ..., -1.06167005,
         0.3113174 ,  1.22359794],
       [-1.21803301, -1.86556575, -1.09350373, ...,  0.29318626,
        -0.02215534,  0.26701273],
       ...,
       [ 1.16893919, -1.01478589,  0.70909301, ...,  0.25583819,
        -1.1510105 ,  0.43475184],
       [-3.04984242,  2.75659527, -1.19806471, ..., -0.02440106,
         0.81747734,  0.42765253],
       [ 1.00474486, -2.77620919,  0.35912631, ...,  0.15225887,
        -0.10820023,  0.22130719]])

#### Creating DataFrame

In [29]:
def col_pc_n(n):

    col = []
    p = 'pc'

    for i in range(0,n):
        col_n = p + str(i)
        col.append(col_n)

    return col

In [30]:
wn_scaled_pca_xtest = pd.DataFrame(pcs_8_xtest, columns=col_pc_n(8))

wn_scaled_pca_xtest

pc0       pc1       pc2       pc3       pc4       pc5       pc6  \
0     -0.792740  2.631812  1.041241 -2.456277 -0.124576  0.171591 -0.823259   
1     -3.354009 -1.000444  0.447770  0.602996 -2.075589 -1.061670  0.311317   
2     -1.218033 -1.865566 -1.093504  0.223988 -0.918474  0.293186 -0.022155   
3     -0.883013  1.005650  1.362120  0.163499  1.420322 -0.972292  0.282115   
4     -2.970749  4.084010  2.596862 -1.414646  0.208905  0.743810 -1.186868   
...         ...       ...       ...       ...       ...       ...       ...   
10189 -0.942593  1.443672  0.614865 -2.409930  0.133344  0.733941 -1.178000   
10190  1.296454  0.024872  0.512759  1.001498 -0.378405 -0.195955  0.420847   
10191  1.168939 -1.014786  0.709093  0.146537  1.388136  0.255838 -1.151011   
10192 -3.049842  2.756595 -1.198065 -1.393759 -0.257365 -0.024401  0.817477   
10193  1.004745 -2.776209  0.359126 -0.984207 -1.097826  0.152259 -0.108200   

            pc7  
0     -0.353735  
1      1.223598  
2      0.267013  
3      0.242936  
4     -0.907490  
...         ...  
10189 -0.672553  
10190 -0.957130  
10191  0.434752  
10192  0.427653  
10193  0.221307  

[10194 rows x 8 columns]

## Exporting Dataframe

In [31]:
wn_scaled_pca.to_csv('xtrain.csv', index=False)
wn_scaled_pca_xtest.to_csv('xtest.csv', index=False)
ytrain.to_csv('ytrain.csv', index=False)
ytest.to_csv('ytest.csv', index=False)